### ISSUE TITLE
Discovery forking mechanism 

### ISSUE THREAD

**Issue by y0sher** [ssvlabs/ssv#1664]
### Description 

We witnessed in mainnet and our stage environment that ETH nodes are filling our discovery routing tables and that we have to go through some eth nodes before finding a SSV node when selecting from the nodes we have in our discovery, this in turn slows down the process to connect to SSV nodes, reducing network connectivity and might hurt our performance. 

### Solution 
Through experiments in our staging ENV we discovered the `ProtocolID` property in DiscV5, while setting this to be `SSVV5` we could block all other protocols that use similar discovery but not running on SSV (mainly the ETH nodes mentioned above).
We implemented this in our stage branch and it works once deployed on both all nodes and bootnode.

### Task 

This task is about getting ready to switch mainnet to use this approach, this is a part of forking to Alan.

- Run two instances of discV5, one of them should work with protocol ID and one without. (Protocol ID can be the domaintype, might need padding)
- use structure similar to discv5's sharedUDPConn to handle the messages passed to `Unhandled` (a config property of discv5) channel which message that could not be handled is passed into. 
- On fork epoch stop listening to the old (no protocol id) version of our discv5, or at least don't start if we are after fork epoch.
- Run 2 bootnodes, one with and one without protocol id and use both. 
- task forking on stage

**Comment by moshe-blox** [comment]
> Protocol ID can be the domaintype
this would be a bit of a problem for us when we want to test multiple domain types in parallel
we can have it NetworkConfig, or if we think its a bit unrelated there, then we can use the domain type unless the config.yaml  overrides it

**Comment by MatheusFranco99** [comment]
We were probably allowing nodes from other networks/protocols due to [this](https://github.com/ethereum/devp2p/blob/master/discv5/discv5.md#comparison-with-other-discovery-mechanisms):
> The Node Discovery Protocol doesn't rely on a single operator and places a small amount of trust in every participant. It becomes more resistant to censorship as the size of the network increases and participants of multiple distinct peer-to-peer networks can share the discovery network to further increase its resilience.

A bigger network is desirable for discovery because it makes it more robust (though it's never safe). However, it shouldn't be a problem since we have some hundreds of operators already.

I'm confused about using the ProtocolID as the DomainType, and not simply using a constant tag like `SSV`. On a fork epoch, all handshakes would start again, all topic advertisements, and so on. But the discovery shouldn't suffer this because of protocol changes, no?
Wdyt @y0sher @moshe-blox ?

The idea is to have two bootnodes (one with and one without ProtocolID) and also two discovery instances running in parallel. Is that right, @y0sher ? I think that's the way since we can't prune the non-SSV nodes from the current discovery network (or at least I don't see how yet)

**Comment by y0sher** [comment]
> We were probably allowing nodes from other networks/protocols due to [this](https://github.com/ethereum/devp2p/blob/master/discv5/discv5.md#comparison-with-other-discovery-mechanisms):
> 
> > The Node Discovery Protocol doesn't rely on a single operator and places a small amount of trust in every participant. It becomes more resistant to censorship as the size of the network increases and participants of multiple distinct peer-to-peer networks can share the discovery network to further increase its resilience.
> 
> A bigger network is desirable for discovery because it makes it more robust (though it's never safe). However, it shouldn't be a problem since we have some hundreds of operators already.
> 
> I'm confused about using the ProtocolID as the DomainType, and not simply using a constant tag like `SSV`. On a fork epoch, all handshakes would start again, all topic advertisements, and so on. But the discovery shouldn't suffer this because of protocol changes, no? Wdyt @y0sher @moshe-blox ?
> 
> The idea is to have two bootnodes (one with and one without ProtocolID) and also two discovery instances running in parallel. Is that right, @y0sher ? I think that's the way since we can't prune the non-SSV nodes from the current discovery network (or at least I don't see how yet)

I think we settled up on not using the DomainType, this was just an idea but it seems it won't be good for us. Also I think we don't need 2 bootnodes! one bootnode that has both discovery instances running as well might be enough..
